-- Run this in Supabase SQL Editor.
-- It creates the core schema for links.ngo profiles.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  tagline text,
  bio text,
  avatar_url text,
  profile_theme text not null default 'futurist',
  profile_layout text not null default 'stack',
  avatar_frame text not null default 'ring',
  link_style text not null default 'glass',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint username_format check (
    username is null
    or (
      username = lower(username)
      and username ~ '^[a-z0-9](?:[a-z0-9_]{1,28}[a-z0-9])?$'
    )
  )
);

create table if not exists public.profile_links (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  label text not null,
  url text not null,
  kind text not null default 'project',
  platform text,
  position integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint profile_links_kind_check check (kind in ('project', 'social'))
);

alter table public.profile_links add column if not exists image_url text;
alter table public.profiles add column if not exists profile_theme text not null default 'futurist';
alter table public.profiles add column if not exists profile_layout text not null default 'stack';
alter table public.profiles add column if not exists avatar_frame text not null default 'ring';
alter table public.profiles add column if not exists link_style text not null default 'glass';

create index if not exists profiles_username_idx on public.profiles (username);
create index if not exists profile_links_profile_id_idx on public.profile_links (profile_id);
create index if not exists profile_links_profile_position_idx on public.profile_links (profile_id, position, created_at);

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_current_timestamp_updated_at();

create or replace trigger set_profile_links_updated_at
before update on public.profile_links
for each row execute procedure public.set_current_timestamp_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user_profile();

alter table public.profiles enable row level security;
alter table public.profile_links enable row level security;

drop policy if exists "profiles_public_read" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_delete_own" on public.profiles;

drop policy if exists "profile_links_public_read" on public.profile_links;
drop policy if exists "profile_links_insert_own" on public.profile_links;
drop policy if exists "profile_links_update_own" on public.profile_links;
drop policy if exists "profile_links_delete_own" on public.profile_links;

create policy "profiles_public_read"
on public.profiles
for select
using (true);

create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = id);

create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "profiles_delete_own"
on public.profiles
for delete
using (auth.uid() = id);

create policy "profile_links_public_read"
on public.profile_links
for select
using (is_active = true or auth.uid() = profile_id);

create policy "profile_links_insert_own"
on public.profile_links
for insert
with check (auth.uid() = profile_id);

create policy "profile_links_update_own"
on public.profile_links
for update
using (auth.uid() = profile_id)
with check (auth.uid() = profile_id);

create policy "profile_links_delete_own"
on public.profile_links
for delete
using (auth.uid() = profile_id);

-- Supabase Storage buckets for profile avatars and link images.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'avatars',
    'avatars',
    true,
    6291456,
    array['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/svg+xml']
  ),
  (
    'link-images',
    'link-images',
    true,
    6291456,
    array['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/svg+xml']
  )
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "avatars_public_read" on storage.objects;
drop policy if exists "avatars_insert_own_folder" on storage.objects;
drop policy if exists "avatars_update_own_folder" on storage.objects;
drop policy if exists "avatars_delete_own_folder" on storage.objects;

drop policy if exists "link_images_public_read" on storage.objects;
drop policy if exists "link_images_insert_own_folder" on storage.objects;
drop policy if exists "link_images_update_own_folder" on storage.objects;
drop policy if exists "link_images_delete_own_folder" on storage.objects;

create policy "avatars_public_read"
on storage.objects
for select
using (bucket_id = 'avatars');

create policy "avatars_insert_own_folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "avatars_update_own_folder"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "avatars_delete_own_folder"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "link_images_public_read"
on storage.objects
for select
using (bucket_id = 'link-images');

create policy "link_images_insert_own_folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'link-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "link_images_update_own_folder"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'link-images'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'link-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "link_images_delete_own_folder"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'link-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);


